# Generated by Django 5.1.3 on 2024-11-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_supplier_products_supplier_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='movement_type',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_removed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
