# Generated by Django 5.1.3 on 2024-11-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_stockmovement_movement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('', 'None'), ('IN', 'In'), ('OUT', 'Out')], default='', max_length=10),
        ),
    ]
